import { StoreProvider } from '@/redux/StoreProvider'
import { Header } from '@/ui/header/page'
import { Inter } from 'next/font/google'
import { Footer } from '@/ui/footer/page'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <Header />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  )
}
